# -- Carregando o Tidyverse e Ggcorrplot --
```{r}
# install.packages("tidyverse")
library(tidyverse)
# install.packages("ggcorrplot")
library(ggcorrplot)
```

# -- Carregando os dados tratados --
```{r}
dados = read_csv("../data/clean/starwars_clean.csv")
View(dados)
```

# -- Analisando correlação entre "altura" e "massa" --
```{r}

correl = dados %>%
  select(altura, massa) %>%
  cor(use="complete.obs")

correl_filt = dados %>%
  filter(massa < 1000) %>% 
  select(altura, massa) %>%
  cor(use="complete.obs")

ggcorrplot(correl_filt,
           lab=T,
           lab_size = 3.5)

ggcorrplot(correl,
           lab=T,
           lab_size = 3.5)
```

# -- Confirmando existência de correlação com gráfico de dispersão --
```{r}

dados %>%
  ggplot(aes(x=altura, y=massa)) +
  geom_point() + geom_smooth(method="lm")

dados %>%
  filter(massa < 1000) %>%
  ggplot(aes(x=altura, y=massa)) +
  geom_point() + geom_smooth(method="lm") +
  geom_vline(xintercept=165, linetype="dotted") +
  geom_hline(yintercept=70, linetype="dotted")
```

# -- Analisando proporções de gêneros --
```{r}
genero = dados %>%
  group_by(genero) %>%
  summarise(n = n())

dados %>%
  filter(genero %in% c("feminine", "masculine")) %>%
  group_by(genero, cor_olho) %>%
  summarise(n = n())

genero %>%
  mutate(genero = case_match(genero,
                             "masculine" ~ "Masculino",
                             "feminine" ~ "Feminino",
                             "not specified" ~ "Não especificado"
                             ),
         percent = (n / sum(n)) * 100,
         p_label = paste0(n, " (", round(percent, 1), "%)")
         ) %>%
  ggplot(aes(x = "", y = n, fill = genero)) +
  geom_bar(stat="identity", width=0.5) +
  coord_flip() +
  geom_text(aes(label = p_label), 
            position = position_stack(vjust = 0.5)) +
  theme_void() +
  labs(
    title = "Proporção dos gêneros",
    fill = "Gêneros"
  )
```

# -- Analisando frequência de mundos natais --
```{r}
dados_resumidos = dados %>%
  filter(!is.na(mundo_natal)) %>%
  group_by(mundo_natal) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  slice_max(n, n = 8)

dados_resumidos %>%
  ggplot(aes(x=reorder(mundo_natal, n), y = n, fill=mundo_natal)) +
  geom_bar(stat="identity") +
  scale_fill_manual(values = c(
    "Alderaan" = "#A8D0E6",
    "Corellia" = "#F7CCAC",
    "Coruscant" = "#C6E2E9",
    "Kamino" = "#F1E0AC",
    "Kashyyyk" = "#E1BBEE",
    "Mirial" = "#FFD5E5",
    "Naboo" = "#E5989B",
    "Ryloth" = "#D4E09B",
    "Tanooine" = "#DBE3E5"
  )) + theme_minimal() + labs(
    title = "Mundo natais com maior frequência",
    x = "Mundo",
    y = "Frequência",
    fill = "Mundos"
  )
```

# -- Analisando frequência de espécies --
```{r}
especies_resumido = dados %>%
  filter(especie != "not specified") %>%
  group_by(especie) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  slice_max(n, n = 9, with_ties = F)

especies_resumido %>%
  mutate(especie = case_match(especie,
                              "Human" ~ "Humano",
                              .default = especie
                              )) %>%
  ggplot(aes(x=reorder(especie, n), y = n, fill=especie)) +
  geom_bar(stat="identity") +
  labs(
    title = "Frequência do número de espécies",
    x = "Espécies",
    y = "Frequência",
    fill = "Espécies"
  ) +
  scale_fill_manual(values = c(
    "Humano"    = "#2C3E50",
    "Droid"    = "#7F8C8D", 
    "Aleena"   = "#E74C3C", 
    "Gungan"   = "#27AE60", 
    "Kaminoan" = "#3498DB", 
    "Mirialan" = "#F1C40F", 
    "Twi'lek"  = "#9B59B6", 
    "Wookiee"  = "#A04000", 
    "Zabrak"   = "#E67E22"  
  )) + coord_flip()
```
